"""
Pre-initialization for FloorPlan4 task.
FloorPlan4 needs to move the tomato out of the fridge
Object dictionary: {'Apple': {'|-02.48|+01.18|+00.48': 1}, 'Bowl': {'|-00.50|+01.04|+02.22': 1}, 
'Bread': {'|-00.18|+01.12|+01.89': 1}, 'ButterKnife': {'|-02.63|+01.11|+00.60': 1}, 
'Cabinet': {'|-01.73|+00.39|+00.73': 1, '|-01.00|+00.39|+00.73': 2}, 'CoffeeMachine': {'|-00.15|+01.04|+03.19': 1}, 
'CounterTop': {'|-00.52|+01.16|+00.49': 1, '|-02.28|+01.16|+00.38': 2, '|-03.86|+01.16|+00.38': 3}, 
'Cup': {'|-01.58|+00.92|+00.34': 1}, 'DiningTable': {'|-00.62|+00.02|+02.49': 1}, 'DishSponge': {'|-01.12|+01.15|+00.09': 1}, 
'Drawer': {'|-02.50|+00.61|+00.59': 1, '|-02.50|+00.22|+00.59': 2, '|-02.04|+00.61|+00.59': 3, '|-02.04|+00.22|+00.59': 4, '|-02.04|+00.94|+00.60': 5, '|-02.51|+00.94|+00.60': 6},
 'Egg': {'|-03.37|+01.30|+02.85': 1}, 'Faucet': {'|-01.37|+01.14|+00.13': 1}, 'Floor': {'|+00.00|+00.00|+00.00': 1}, 
 'Fork': {'|-00.46|+01.04|+01.78': 1}, 'Fridge': {'|-03.52|+00.00|+02.72': 1}, 'GarbageCan': {'|-03.70|+00.00|+02.01': 1},
   'HousePlant': {'|-02.16|+01.10|+00.17': 1}, 'Knife': {'|-01.48|+00.93|+00.42': 1}, 'Ladle': {'|-01.95|+01.14|+00.45': 1},
     'Lettuce': {'|-03.31|+00.97|+03.04': 1}, 'LightSwitch': {'|-02.58|+01.30|+03.50': 1}, 'Microwave': {'|-00.37|+01.11|+00.43': 1}, 
     'Mug': {'|-00.38|+01.09|+03.19': 1}, 'Pan': {'|-00.27|+01.04|+02.56': 1}, 'PepperShaker': {'|-03.76|+01.11|+00.39': 1}, 
     'Plate': {'|-01.19|+00.92|+00.40': 1}, 'Pot': {'|-03.00|+01.14|+00.48': 1}, 'Potato': {'|-02.66|+01.15|+00.25': 1},
       'SaltShaker': {'|-03.76|+01.11|+00.52': 1}, 'Sink': {'|-01.39|+00.98|+00.44': 1, '|-01.39|+00.98|+00.44|SinkBasin': 2}, 
       'SoapBottle': {'|-00.89|+01.11|+00.19': 1}, 'Spatula': {'|-00.81|+01.12|+00.53': 1}, 'Spoon': {'|-00.43|+01.04|+01.90': 1}, 
       'StoveBurner': {'|-03.00|+01.10|+00.23': 1, '|-03.48|+01.10|+00.23': 2, '|-03.00|+01.10|+00.48': 3, '|-03.48|+01.10|+00.48': 4}, 
       'StoveKnob': {'|-03.16|+01.05|+00.71': 1, '|-03.49|+01.05|+00.71': 2, '|-02.99|+01.05|+00.71': 3, '|-03.32|+01.05|+00.71': 4}, ''Toaster': {'|-00.23|+01.04|+02.87': 1}, 
       'Tomato': {'|-00.75|+01.08|+02.40': 1}, 'Window': {'|-01.39|+01.93|+00.02': 1, '|-03.27|+01.93|+00.02': 2}}
"""

class SceneInitializer:
    def __init__(self) -> None:
        pass

    def preinit(self, event, controller):
        """Pre-initialize the environment for the task.

        Args:
            event: env.event object
            controller: ai2thor.controller object

        Returns:
            event: env.event object

            |-02.63|+01.11|+00.60 butter knife countertop
            Spatula': {'|-00.81|+01.12|+00.53': 1}
        """

            # initialization function - autogenerated
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Bread|-00.18|+01.12|+01.89',
        position={'x': -2.64400000035762787, 'y': 1.1191563606262207, 'z': 0.6019998407363892}
        )
        print("Moving Bread")

        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Tomato|-00.75|+01.08|+02.40',
        position={'x': -1.4868804717063904, 'y': 1.0815153121948242, 'z': 0.4195256423950195}
        )
        print("Moving Tomato|-01.48|+00.93|+00.42")

        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Lettuce|-03.31|+00.97|+03.04',
        position={'x': -0.8064676165580748, 'y': 1.9657654047012327, 'z': 0.5488126707077026}
        )
        print("Moving Lettuce")
        
        event=controller.step(
        action='PlaceObjectAtPoint',
        objectId='Egg|-03.37|+01.30|+02.85',
        position={'x': -0.754676165580748, 'y': 1.1815153121948242, 'z': 2.588126707077026}
        )
        

        return event
